name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      # Optional: Upload the build artifacts
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos/